//React basic imports
import React, {Component} from 'react';

//Style imports
import './style.css';

export default class FilePreview extends Component{

  render(){

    let string = this.props.file.forFilePreview.map((word, index) =>{ //Populate the array
      let theWord = word.toLowerCase()
      return (
        <span key={index /*Only needed between sibling generated by array*/}>
          {/*The active class will highlight the current word*/}
          <span className={this.props.currentWord === theWord ? 'active': ''}>{word}</span>
          <span>&nbsp;</span> {/*Add an extra space after each word*/}
        </span>
        )
    });

    return (
      <div className="pl-1">
        <h1>{this.props.file.fileTitle}</h1>
        <div className="h4">{string /*Naturally, the array will unpack*/}</div>
      </div>
    );
  }
}
