//React basic imports
import React, {Component} from 'react';

//Style imports
import './style.css';

export default class FilePreview extends Component{
  constructor(props){
    super(props);

    this.dummyTest = "Hello there, this's a dummy test.\nUsed only for testing, don't mind it";

  }

  render(){

    let string = this.dummyTest.split(' ').map((word, index) =>{ //Populate the array
      let theWord = word.toLowerCase()
      return (
        <span key={index /*Only needed between sibling generated by array*/}>
          {/*The active class will highlight the current word*/}
          <span className={this.props.currentWord === theWord ? 'active': ''}>{word}</span>
          <span> </span> {/*Add an extra space after each word*/}
        </span>
        )
    });

    return (
      <div className="pl-1">
        <h1>File Title Here</h1>
        <pre className="pre h4">{string /*Naturally, the array will unpack*/}</pre>
      </div>
    );
  }
}
